---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
---

<div style="text-align: center;">
<h1>Interactive map <i class="fas fa-map"></i></h1>
</div>

## Map context

<p class = "text"> On this page, we can see two interactive maps of bicycle traffic in the city of Montpellier: one corresponds to the predictions that we made from the data from January 2023 to June 2023, and the other on the actual data we have for this period. We decided to represent the two cards so that we could make a compari </p>

<p class = "text"> The interactive maps below show the forecast of cycling/ real cycling in the city of Montpellier from 10 July to 16 July 2023. These dates represent the intermediate week (2nd of 3 weeks) of the Tour de France.</p>

## Maps

### Predictions' methods

<p class = "text"> The bicycle traffic predictions were made using the ‘Prophet’ model, a flexible tool for time series analysis. This model is well suited to data with temporal variations, making it an ideal choice for modelling cycle traffic. The prediction was influenced by factors such as days of the week, weather and local events (such as the Tour de France). The predictions generated by Prophet have been integrated into the interactive map, making it possible to visualise predicted traffic levels on the various routes between stations. To make this prediction, we decided to calculate only the shortest paths between each of the stations and not all the possible paths, for the sake of optimising journey times and also to make the map easier to read. </p>

### Graphs

<p class = "text"> In this maps, several days can be selected at the same time, but we advise you to select the days one after the other for consistent predictions. </p>

<p class = "text"> Map of the **cycling traffic forecast** in Montpellier during the second week of the Tour de France: </p>

<iframe src="/images/bike_traffic_prediction_map.html" width="100%" height="400px" frameborder="0"></iframe>

<p class = "text"> Map of the **cycling traffic** in Montpellier during the second week of the Tour de France: </p>

<iframe src="/images/real_data_map.html" width="100%" height="400px" frameborder="0"></iframe>

### Cycle stations (Eco-counters)

<p class = "text"> The stations are represented by blue markers distributed around the city. </p>

### Paths between stations

<p class = "text">The lines connecting the stations correspond to the paths between them. The colours of the lines vary according to the number of cycles predicted to pass along the route: </p>

<ul class = "text"> 
    <li> Red: Very high intensity (> 1500). </li>
    <li> Orange: High intensity (1201-1500). </li>
    <li> Brown: Moderate intensity (901-1200) </li>
    <li> Yellow: Moderate intensity (601-900). </li>
    <li> Light green: Low intensity (301-600). </li>
    <li> Dark green: Very low intensity (<= 300). </li>
</ul>

### Geographical coverage

<p class = "text"> Predictions cover a 15km radius around Montpellier, including areas such as Saint-Jean-de-Védas, Castelnau-le-Lez, and Villeneuve-lès-Maguelone. We decided not to extend this area because bike journeys were becoming rare and we weren't sure whether a station further away would actually correspond to a journey between that station and Montpellier or just a journey within its city. </p>

## Comparisons

### Between maps

### Between days 
