---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
---

<div style="text-align: center;">
<h1>Videos <i class="fas fa-video"></i></h1>
</div>

## Presentation

<<<<<<< HEAD
<p class = "text"> On this page, we will present you a video of the routes of the bicycles Velomag in the city of Montpellier for the date of Monday, July 10, 2023. This date corresponds to the first day of the second week of the Tour de France. </p>
=======
<p class = "text"> This section presents an animated video visualizing the cyclists' journeys during a specific day of the 2023 Tour de France. It highlights cycling activity in Montpellier using data from the VéloMagg system. </p>
>>>>>>> 106c1d70ba8c865cbdfc7711f8297ac699874776

<p class = "text"> This allows us to deepen the results we have obtained in the maps game and will allow us to look at what is happening in terms of traffic of cyclists during the different hours of a day. </p>

<p class = "text"> We decided to choose a day of the week because we could notice on the maps that there was less traffic during the weekend.</p>

## Videos

<<<<<<< HEAD
<div class="container"> <div class="video-container"> <video src="/images/Bike_Animation_10-07-2023.MOV" controls></video> </div> <div class="text"> <p>Monday 10 July 2023</p> </div> </div>

<div class="container-r"> <div class="video-container-r"> <video src="/images/video_1.mp4" controls></video> </div> <div class="text"> <p>Tuesday 11 July 2023</p> </div> </div>

<div class="container"> <div class="video-container"> <video src="/images/video_1.mp4" controls></video> </div> <div class="text"> <p>Wednesday 12 July 2023</p> </div> </div>

## Analyses

=======
<div class="container"> <div class="video-container"> 
<iframe src="https://www.youtube.com/embed/Gc6I6s13_JY " frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen width="800" height="450"></iframe></div> <div class="text"> <p>Monday 10 July 2023</p> </div> </div>
>>>>>>> 106c1d70ba8c865cbdfc7711f8297ac699874776
