---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
---

<div style="text-align: center;">
<h1>Privacy policy <i class="fas fa-lock"></i></h1>
</div>

<p class = "text"> EFFECTIVE DATE: 2024-12-10 </p>

<p class = "text"> Welcome to the site made by BikeProjectTeam7. We value your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, and share your information. </p>

## Information We Collect

<p class = "text"> We may collect the following types of information:
Personal Information: name, email address.
Usage Data: information on how you use our site (e.g., pages visited, time spent on the site). </p>

<p class = "text">  Cookies and Tracking Technologies: we do not use cookies. </p>

## How We Use Your Information

<p class = "text">  We use your information to: </p>

<ul class = "text">
    <li>Provide and maintain our services.</li>
    <li>Improve the user experience on our site.</li>
</ul>

## Data Sharing and Disclosure

<p class = "text">  We do not sell your personal data. </p>

## Your Rights

<p class = "text"> You have the right to: </p>

<ul class = "text"> 
    <li>Access your personal data.</li>
    <li>Request correction or deletion of your data.</li>
    <li>Opt out of data collection. </li>
</ul>

## Contact Us

<p class = "text"> If you have any questions or concerns about this Privacy Policy, please contact us at <a href="about_us.html#mail">your email address</a>. </p>

