---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
---

<div style="text-align: center;">
<h1>Packages <i class="fas fa-book-open"></i></h1>
</div>

<p class = "text"> For the necessary codes for our project, we have used some packages to make our analysis. </p>

### 'Numpy'

<p class = "text"> This package was used to perform efficient numerical computations, by manipulating multidimensional arrays and carrying out mathematical, statistical, and algebraic operations on these arrays.</p>

<p class = "text"> For more details we can consult the <a href="https://numpy.org/doc/">documentation</a> of this packages. </p>

### 'Pandas'

<p class = "text"> This package was used to manipulate and analyze data, primarily by structuring data into DataFrames and performing operations like cleaning, filtering, aggregation, and statistical analysis. </p>

<p class = "text"> For more details we can consult the <a href="https://pandas.pydata.org/docs/">documentation</a> of this packages. </p>

### 'Matplotlib'

<p class = "text"> This package was used to create graphical visualizations, such as line plots, histograms, bar charts, etc., to better understand and analyze the data.</p>

<p class = "text"> For more details we can consult the <a href="https://matplotlib.org/stable/index.html">documentation</a> of this packages. </p>

### 'Pooch'

<p class = "text"> This package was used to download and manage files reliably, especially for projects that require downloading external files (such as datasets) while ensuring version control and file integrity. </p>

<p class = "text"> For more details we can consult the <a href="https://www.fatiando.org/pooch/latest/">documentation</a> of this packages. </p>

### 'Geopy'
<p class = "text"> This package was used to calculate the distance between two geographical coordinates to determine the optimal route between multiple points in a logistics application. </p>

<p class = "text"> For more details we can consult the <a href=" https://geopy.readthedocs.io/en/stable/">documentation</a> of this packages. </p>

### 'Osmnx'
<p class = "text"> This package was used to download and analyze the bike-friendly road network of Montpellier from OpenStreetMap data. It enabled the visualization of the network, calculation of optimal routes for cycling, and analysis of the connectivity and structure of the cycling paths. </p>

<p class = "text"> For more details we can consult the <a href="https://osmnx.readthedocs.io/en/stable/">documentation</a> of this packages. </p>

### 'Seaborn'
<p class = "text"> This package was used to create elegant and informative statistical visualizations, such as distribution plots and scatterplots, to explore and understand the relationships between variables in the analyzed data </p>

<p class = "text"> For more details we can consult the <a href=" https://seaborn.pydata.org/">documentation</a> of this packages. </p>

### 'Tqdm'
<p class = "text">This package was used to add progress bars to loops, allowing users to visually track the progress of a process, especially during long or repetitive tasks. </p>

<p class = "text"> For more details we can consult the <a href="https://tqdm.github.io/">documentation</a> of this packages. </p>

### 'Moviepy'
<p class = "text"> This package was used to create a video from images, by assembling them in a specific order to form a smooth video sequence. </p>

<p class = "text"> For more details we can consult the <a href="https://moviepy.readthedocs.io/en/latest/">documentation</a> of this packages. </p>