---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
---

<div style="text-align: center;">
<h1>Privacy polity <i class="fas fa-lock"></i></h1>
</div>

## Introduction

<p class = "text"> Welcome to BikeProjectTeam7. We value your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, and share your information. </p>

### 1. Information We Collect

<p class = "text"> We may collect the following types of information:
Personal Information: Name, email address, phone number (when you fill out a form or subscribe to our newsletter).
Usage Data: Information on how you use our site (e.g., pages visited, time spent on the site). </p>

<p class = "text">  Cookies and Tracking Technologies: We use cookies to enhance user experience and analyze site traffic. </p>

### 2. How We Use Your Information

<p class = "text">  We use your information to: </p>

<ul class = "text">
    <li>Provide and maintain our services.</li>
    <li>Improve the user experience on our site.</li>
    <li>Send you promotional content if you’ve opted in.</li>
</ul>

### 3. Data Sharing and Disclosure

<p class = "text">  We do not sell your personal data. We may share information with trusted third-party providers for analytics or marketing purposes (e.g., Google Analytics). </p>

### 4. Your Rights

<p class = "text"> You have the right to: </p>

<ul class = "text"> 
    <li>Access your personal data.</li>
    <li>Request correction or deletion of your data.</li>
    <li>Opt out of data collection (e.g., disable cookies). </li>
</ul>

### 5. Contact Us

<p class = "text"> If you have any questions or concerns about this Privacy Policy, please contact us at <a href="about_us.html#mail">your email address</a>. </p>

