---
format:
  html:
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
---

<div style="text-align: center;">
<h1>Terms and Conditions <i class="fas fa-file-contract"></i></h1>
</div>

<p class = "text"> These Terms & Conditions govern your use of our website BikeProjectTeam7. By accessing or using our site, you agree to comply with these Terms. </p>

#### 1. Use of the Website

<p class = "text"> You may use this website for personal and non-commercial purposes. You agree not to: </p>

<ul class = "text"> 
    <li>Post any unlawful or harmful content.</li>
    <li>Attempt to gain unauthorized access to the website or its systems.</li>
    <li>Use the website for fraudulent purposes. </li>
</ul>

#### 2. Intellectual Property

<p class = "text"> All content on this site, including text, images, and logos, is the property of [Your Website Name]. Unauthorized use of any content is prohibited. </p>

#### 3. Limitation of Liability

<p class = "text"> We are not responsible for any errors, interruptions, or losses that may occur while using our website. The content is provided "as is" without any warranties. </p>

#### 4. Changes to Terms

<p class = "text"> We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting on this page. Please review the Terms regularly. </p>

#### 5. Governing Law

<p class = "text"> These Terms are governed by the laws of [Your Country/Region]. Any disputes arising from these Terms will be resolved in the courts of [Your Country/Region]. </p>

#### 6. Contact Us

<p class = "text"> If you have any questions about these Terms, please contact us at <a href="about_us.html#mail">your email address</a>. </p>